[package]
name = "game_jam"
version = "0.1.0"
authors = ["andresattler <andressattler.webdev@gmail.com>", "Paul Martensen <paul.martensen@gmx.de>"]
edition = "2018"

[dependencies]
rand = "0.6.0"
nalgebra = "*"
kiss3d = "*"
